directories:
  data_directory: data/docs
  data_directory_2: data/docs_2
  persist_directory: data/vectordb/processed/chroma/
  custom_persist_directory: data/vectordb/uploaded/chroma/
  
embedding_model_config:
   #engine: "text-emb-3-large"
  #engine: "text-emb-ada-002"
  #engine: "text-emb-ada-002"
  engine: "text-embedding-ada-002"

llm_config:
    llm_system_role: "You are a chatbot. You'll receive a prompt that includes a chat history, retrieved content from the vectorDB based on the user's question, and the source.\ 
    Your task is to respond to the user's new question using the information from the vectorDB without relying on your own knowledge and also transalte the response in Japanese.\
    you will receive a prompt with the the following format:

    # Chat history:\n
    [user query, response]\n\n

    # Retrieved content number:\n
    Content\n\n
    Source\n\n

    # User question:\n
    New question
    "
    #engine: "gpt-35-trubo-0125"
    engine: "gpt-35-turbo-0125"
    temperature: 0.0
    max_token: 50000

summarizer_config:
    max_final_token: 500000
    character_overlap: 100
    token_threshold: 0
    # summarizer_llm_system_role: "You are an expert pdf summarizer. You will receive a text and your task is to summarize and keep all the key information.
    #   don't worry about the length of the summary. Also don`t add the author name, paper name, and publication date in the summary. "
    # final_summarizer_llm_system_role: "Write down the summary point by point of the provided document. The text you collect from abstarct, introduction and comclusion section. You will receive a text and your task is to give a comprehensive summary and don't worry about the length of the summary. Also 
    # dont add the author name, paper name, and publication date in the summary. Also don't add the author name, paper name, and publication date in the summary. Also translate the summary into Japanese. Show me English and Japanese summary."
    

    summarizer_llm_system_role: "You will receive a text and your task is to give a comprehensive summary and keep all the key information. Provide as much key information as necessary and don't try to make it short. "
    final_summarizer_llm_system_role: "You will receive a text and your task is to give a comprehensive summary and keep all the key information. Provide as much key information as necessary and don't try to make it short.Also translate the summary into Japanese. Show me English and Japanese summary."

splitter_config:
  chunk_size: 1500
  chunk_overlap: 500

retrieval_config:
  k: 3

serve:
  port: 8000

memory:
  number_of_q_a_pairs: 2


  
